spring:
  profiles:
    active: dev
---
server:
  port: 8000
#spring配置
spring:
  profiles: dev
  application:
    name: spring-cloud-consumer
#eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
      
----
server:
  port: 8001
#spring配置
spring:
  profiles: test
  application:
    name: spring-cloud-consumer
#eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/